# ------ root_path/dataset_name ------
root_path: /mnt/data


# ------ Load Cache and Features ------
load_cache: False
load_pre_feat: False

# ------ Hyperparamters ------
init_beta: 26
init_alpha: 1
T: 1

# ------ Basic Config ------
dataset: 'oxford_pets'
shots: 16
backbone: 'RN50'
lr: 0.0001
augment_epoch: 10
train_epoch: 5
