# ------ root_path/dataset_name ------
root_path: /mnt/data


# ------ Load Cache and Features ------
load_cache: False
load_pre_feat: False


# ------ Basic Config ------
dataset: 'ucm'
shots: 5
backbone: 'ViT-L/14'
lr: 0.0001
augment_epoch: 10
train_epoch: 5